"""create insights table

Revision ID: 3d17254743b8
Revises: 955917ed64f1
Create Date: 2026-01-18 08:29:07.546896

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d17254743b8'
down_revision: str | Sequence[str] | None = '955917ed64f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_signal_id', sa.UUID(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('proposed_solution', sa.Text(), nullable=False),
    sa.Column('market_size_estimate', sa.String(length=20), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('competitor_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_signal_id'], ['raw_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_created_at'), 'insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_insights_raw_signal_id'), 'insights', ['raw_signal_id'], unique=False)
    op.create_index(op.f('ix_insights_relevance_score'), 'insights', ['relevance_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_relevance_score'), table_name='insights')
    op.drop_index(op.f('ix_insights_raw_signal_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_created_at'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
