"""add_competitor_profiles_and_snapshots_tables

Revision ID: 448430173035
Revises: 29b08a2199f2
Create Date: 2026-01-28 08:50:05.353930

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '448430173035'
down_revision: str | Sequence[str] | None = '29b08a2199f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE custom_analyses DROP CONSTRAINT IF EXISTS custom_analyses_user_id_fkey")
    op.create_foreign_key(None, 'custom_analyses', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('insight_interactions', 'insight_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.execute("ALTER TABLE insight_interactions DROP CONSTRAINT IF EXISTS insight_interactions_insight_id_fkey")
    op.create_foreign_key(None, 'insight_interactions', 'insights', ['insight_id'], ['id'], ondelete='SET NULL')
    op.alter_column('insights', 'community_signals_chart',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Community engagement visualization data (platform, score, members, engagement_rate)',
               existing_nullable=True)
    op.alter_column('insights', 'enhanced_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='8-dimension scoring breakdown (dimension, value, label)',
               existing_nullable=True)
    op.alter_column('insights', 'trend_predictions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Time-series forecast predictions for next 7 days (dates, values, confidence intervals)',
               existing_nullable=True)
    op.execute("DROP INDEX IF EXISTS idx_research_requests_created_at")
    op.execute("DROP INDEX IF EXISTS idx_research_requests_status")
    op.execute("DROP INDEX IF EXISTS idx_research_requests_user_id")
    # Use IF NOT EXISTS guards — these columns may already exist if 68bc7f9b5a31 created them
    op.execute("ALTER TABLE saved_insights ADD COLUMN IF NOT EXISTS insight_title_snapshot TEXT")
    op.execute("ALTER TABLE saved_insights ADD COLUMN IF NOT EXISTS insight_problem_snapshot TEXT")
    op.alter_column('saved_insights', 'insight_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.execute("ALTER TABLE saved_insights DROP CONSTRAINT IF EXISTS saved_insights_insight_id_fkey")
    op.create_foreign_key(None, 'saved_insights', 'insights', ['insight_id'], ['id'], ondelete='SET NULL')
    op.execute("CREATE INDEX IF NOT EXISTS ix_shared_insights_shared_by_id ON shared_insights (shared_by_id)")
    op.execute("ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS user_email_snapshot VARCHAR(255)")
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.execute("ALTER TABLE subscriptions DROP CONSTRAINT IF EXISTS subscriptions_user_id_fkey")
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.execute("CREATE INDEX IF NOT EXISTS ix_team_invitations_invited_by_id ON team_invitations (invited_by_id)")
    op.alter_column('user_ratings', 'insight_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.execute("ALTER TABLE user_ratings DROP CONSTRAINT IF EXISTS user_ratings_insight_id_fkey")
    op.create_foreign_key(None, 'user_ratings', 'insights', ['insight_id'], ['id'], ondelete='SET NULL')
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_by UUID")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS deletion_reason TEXT")
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_deleted_at ON users (deleted_at)")
    op.execute("DROP INDEX IF EXISTS ix_webhook_events_created_at")
    op.execute("ALTER TABLE webhook_events DROP CONSTRAINT IF EXISTS uq_webhook_events_stripe_event_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_webhook_events_stripe_event_id'), 'webhook_events', ['stripe_event_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_webhook_events_created_at'), 'webhook_events', ['created_at'], unique=False)
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deletion_reason')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'user_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('user_ratings_insight_id_fkey'), 'user_ratings', 'insights', ['insight_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_ratings', 'insight_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_team_invitations_invited_by_id'), table_name='team_invitations')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('subscriptions', 'user_email_snapshot')
    op.drop_index(op.f('ix_shared_insights_shared_by_id'), table_name='shared_insights')
    op.drop_constraint(None, 'saved_insights', type_='foreignkey')
    op.create_foreign_key(op.f('saved_insights_insight_id_fkey'), 'saved_insights', 'insights', ['insight_id'], ['id'], ondelete='CASCADE')
    op.alter_column('saved_insights', 'insight_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('saved_insights', 'insight_problem_snapshot')
    op.drop_column('saved_insights', 'insight_title_snapshot')
    op.create_table_comment(
        'research_requests',
        'Research requests submitted by users, pending admin approval',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_research_requests_user_id'), 'research_requests', ['user_id'], unique=False)
    op.create_index(op.f('idx_research_requests_status'), 'research_requests', ['status'], unique=False)
    op.create_index(op.f('idx_research_requests_created_at'), 'research_requests', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('insights', 'trend_predictions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Time-series forecast predictions for next 7 days (dates, values, confidence intervals)',
               existing_nullable=True)
    op.alter_column('insights', 'enhanced_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='8-dimension scoring breakdown (dimension, value, label)',
               existing_nullable=True)
    op.alter_column('insights', 'community_signals_chart',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Community engagement visualization data (platform, score, members, engagement_rate)',
               existing_nullable=True)
    op.drop_constraint(None, 'insight_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('insight_interactions_insight_id_fkey'), 'insight_interactions', 'insights', ['insight_id'], ['id'], ondelete='CASCADE')
    op.alter_column('insight_interactions', 'insight_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'custom_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('custom_analyses_user_id_fkey'), 'custom_analyses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
