"""Phase 6-7: Subscriptions, Teams, API Keys, and Tenants

Revision ID: 68bc7f9b5a31
Revises: a005_phase_5_1
Create Date: 2026-01-25 09:39:09.198941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68bc7f9b5a31'
down_revision: Union[str, Sequence[str], None] = 'a005_phase_5_1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=False),
    sa.Column('requests_this_hour', sa.Integer(), nullable=False),
    sa.Column('requests_this_day', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_ips', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyses_used_this_month', sa.Integer(), nullable=False),
    sa.Column('last_usage_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_owner_id'), 'teams', ['owner_id'], unique=False)
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('custom_domain_verified', sa.Boolean(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('app_name', sa.String(length=100), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('terms_url', sa.String(length=500), nullable=True),
    sa.Column('privacy_url', sa.String(length=500), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('max_api_keys', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('tenant_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_domain')
    )
    op.create_index(op.f('ix_tenants_owner_id'), 'tenants', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_subdomain'), 'tenants', ['subdomain'], unique=True)
    op.create_table('api_key_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_usage_logs_api_key_id'), 'api_key_usage_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_key_usage_logs_created_at'), 'api_key_usage_logs', ['created_at'], unique=False)
    op.create_table('payment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index(op.f('ix_payment_history_subscription_id'), 'payment_history', ['subscription_id'], unique=False)
    op.create_table('shared_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('shared_by_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'insight_id', name='uq_shared_insight')
    )
    op.create_index(op.f('ix_shared_insights_insight_id'), 'shared_insights', ['insight_id'], unique=False)
    op.create_index(op.f('ix_shared_insights_team_id'), 'shared_insights', ['team_id'], unique=False)
    op.create_table('team_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'email', name='uq_team_invitation')
    )
    op.create_index(op.f('ix_team_invitations_email'), 'team_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_team_invitations_team_id'), 'team_invitations', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_token'), 'team_invitations', ['token'], unique=True)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('tenant_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_users_user_id'), 'tenant_users', ['user_id'], unique=False)
    op.drop_index(op.f('idx_admin_users_role'), table_name='admin_users')
    op.drop_index(op.f('idx_admin_users_user'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_role'), 'admin_users', ['role'], unique=False)
    op.create_index(op.f('ix_admin_users_user_id'), 'admin_users', ['user_id'], unique=False)
    op.drop_index(op.f('idx_agent_logs_created'), table_name='agent_execution_logs')
    op.drop_index(op.f('idx_agent_logs_source'), table_name='agent_execution_logs')
    op.drop_index(op.f('idx_agent_logs_type_status'), table_name='agent_execution_logs')
    op.create_index(op.f('ix_agent_execution_logs_agent_type'), 'agent_execution_logs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_created_at'), 'agent_execution_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_source'), 'agent_execution_logs', ['source'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_status'), 'agent_execution_logs', ['status'], unique=False)
    op.drop_index(op.f('idx_analyses_created'), table_name='custom_analyses')
    op.drop_index(op.f('idx_analyses_status'), table_name='custom_analyses')
    op.drop_index(op.f('idx_analyses_user'), table_name='custom_analyses')
    op.drop_index(op.f('idx_analyses_user_status'), table_name='custom_analyses')
    op.create_index(op.f('ix_custom_analyses_created_at'), 'custom_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_custom_analyses_status'), 'custom_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_custom_analyses_user_id'), 'custom_analyses', ['user_id'], unique=False)
    op.drop_index(op.f('idx_interactions_created'), table_name='insight_interactions')
    op.drop_index(op.f('idx_interactions_insight'), table_name='insight_interactions')
    op.drop_index(op.f('idx_interactions_type'), table_name='insight_interactions')
    op.drop_index(op.f('idx_interactions_type_created'), table_name='insight_interactions')
    op.drop_index(op.f('idx_interactions_user'), table_name='insight_interactions')
    op.drop_index(op.f('idx_interactions_user_insight'), table_name='insight_interactions')
    op.create_index(op.f('ix_insight_interactions_created_at'), 'insight_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_insight_interactions_insight_id'), 'insight_interactions', ['insight_id'], unique=False)
    op.create_index(op.f('ix_insight_interactions_interaction_type'), 'insight_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_insight_interactions_user_id'), 'insight_interactions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_insights_admin_status'), table_name='insights')
    op.drop_index(op.f('idx_insights_edited_by'), table_name='insights')
    op.drop_index(op.f('idx_insights_enhanced_filter'), table_name='insights')
    op.drop_index(op.f('idx_insights_execution'), table_name='insights')
    op.drop_index(op.f('idx_insights_feasibility'), table_name='insights')
    op.drop_index(op.f('idx_insights_founder_fit'), table_name='insights')
    op.drop_index(op.f('idx_insights_go_to_market'), table_name='insights')
    op.drop_index(op.f('idx_insights_opportunity'), table_name='insights')
    op.drop_index(op.f('idx_insights_problem'), table_name='insights')
    op.drop_index(op.f('idx_insights_revenue_potential'), table_name='insights')
    op.drop_index(op.f('idx_insights_why_now'), table_name='insights')
    op.create_index(op.f('ix_insights_execution_difficulty'), 'insights', ['execution_difficulty'], unique=False)
    op.create_index(op.f('ix_insights_feasibility_score'), 'insights', ['feasibility_score'], unique=False)
    op.create_index(op.f('ix_insights_founder_fit_score'), 'insights', ['founder_fit_score'], unique=False)
    op.create_index(op.f('ix_insights_go_to_market_score'), 'insights', ['go_to_market_score'], unique=False)
    op.create_index(op.f('ix_insights_opportunity_score'), 'insights', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_insights_problem_score'), 'insights', ['problem_score'], unique=False)
    op.create_index(op.f('ix_insights_revenue_potential'), 'insights', ['revenue_potential'], unique=False)
    op.create_index(op.f('ix_insights_why_now_score'), 'insights', ['why_now_score'], unique=False)
    op.drop_constraint(op.f('fk_insights_edited_by_admin'), 'insights', type_='foreignkey')
    op.drop_column('insights', 'edited_at')
    op.drop_column('insights', 'admin_notes')
    op.drop_column('insights', 'admin_status')
    op.drop_column('insights', 'admin_override_score')
    op.drop_column('insights', 'edited_by')
    op.drop_index(op.f('idx_saved_insights_insight'), table_name='saved_insights')
    op.drop_index(op.f('idx_saved_insights_user_saved'), table_name='saved_insights')
    op.drop_index(op.f('idx_saved_insights_user_status'), table_name='saved_insights')
    op.create_index(op.f('ix_saved_insights_insight_id'), 'saved_insights', ['insight_id'], unique=False)
    op.create_index(op.f('ix_saved_insights_saved_at'), 'saved_insights', ['saved_at'], unique=False)
    op.create_index(op.f('ix_saved_insights_status'), 'saved_insights', ['status'], unique=False)
    op.create_index(op.f('ix_saved_insights_user_id'), 'saved_insights', ['user_id'], unique=False)
    op.drop_index(op.f('idx_metrics_type'), table_name='system_metrics')
    op.drop_index(op.f('idx_metrics_type_recorded'), table_name='system_metrics')
    op.create_index(op.f('ix_system_metrics_metric_type'), 'system_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_system_metrics_recorded_at'), 'system_metrics', ['recorded_at'], unique=False)
    op.drop_index(op.f('idx_user_ratings_insight'), table_name='user_ratings')
    op.drop_index(op.f('idx_user_ratings_rated'), table_name='user_ratings')
    op.drop_index(op.f('idx_user_ratings_user'), table_name='user_ratings')
    op.create_index(op.f('ix_user_ratings_insight_id'), 'user_ratings', ['insight_id'], unique=False)
    op.create_index(op.f('ix_user_ratings_rated_at'), 'user_ratings', ['rated_at'], unique=False)
    op.create_index(op.f('ix_user_ratings_user_id'), 'user_ratings', ['user_id'], unique=False)
    op.drop_index(op.f('idx_users_created'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_supabase_id'), table_name='users')
    op.drop_index(op.f('idx_users_tier'), table_name='users')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_supabase_id'), 'users', type_='unique')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_subscription_tier'), 'users', ['subscription_tier'], unique=False)
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_tier'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_supabase_id'), 'users', ['supabase_user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_tier'), 'users', ['subscription_tier'], unique=False)
    op.create_index(op.f('idx_users_supabase_id'), 'users', ['supabase_user_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created'), 'users', ['created_at'], unique=False)
    op.drop_index(op.f('ix_user_ratings_user_id'), table_name='user_ratings')
    op.drop_index(op.f('ix_user_ratings_rated_at'), table_name='user_ratings')
    op.drop_index(op.f('ix_user_ratings_insight_id'), table_name='user_ratings')
    op.create_index(op.f('idx_user_ratings_user'), 'user_ratings', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_ratings_rated'), 'user_ratings', ['rated_at'], unique=False)
    op.create_index(op.f('idx_user_ratings_insight'), 'user_ratings', ['insight_id'], unique=False)
    op.drop_index(op.f('ix_system_metrics_recorded_at'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_metric_type'), table_name='system_metrics')
    op.create_index(op.f('idx_metrics_type_recorded'), 'system_metrics', ['metric_type', 'recorded_at'], unique=False)
    op.create_index(op.f('idx_metrics_type'), 'system_metrics', ['metric_type'], unique=False)
    op.drop_index(op.f('ix_saved_insights_user_id'), table_name='saved_insights')
    op.drop_index(op.f('ix_saved_insights_status'), table_name='saved_insights')
    op.drop_index(op.f('ix_saved_insights_saved_at'), table_name='saved_insights')
    op.drop_index(op.f('ix_saved_insights_insight_id'), table_name='saved_insights')
    op.create_index(op.f('idx_saved_insights_user_status'), 'saved_insights', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_saved_insights_user_saved'), 'saved_insights', ['user_id', 'saved_at'], unique=False)
    op.create_index(op.f('idx_saved_insights_insight'), 'saved_insights', ['insight_id'], unique=False)
    op.add_column('insights', sa.Column('edited_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('insights', sa.Column('admin_override_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('insights', sa.Column('admin_status', sa.VARCHAR(length=20), server_default=sa.text("'approved'::character varying"), autoincrement=False, nullable=True))
    op.add_column('insights', sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('insights', sa.Column('edited_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_insights_edited_by_admin'), 'insights', 'admin_users', ['edited_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_insights_why_now_score'), table_name='insights')
    op.drop_index(op.f('ix_insights_revenue_potential'), table_name='insights')
    op.drop_index(op.f('ix_insights_problem_score'), table_name='insights')
    op.drop_index(op.f('ix_insights_opportunity_score'), table_name='insights')
    op.drop_index(op.f('ix_insights_go_to_market_score'), table_name='insights')
    op.drop_index(op.f('ix_insights_founder_fit_score'), table_name='insights')
    op.drop_index(op.f('ix_insights_feasibility_score'), table_name='insights')
    op.drop_index(op.f('ix_insights_execution_difficulty'), table_name='insights')
    op.create_index(op.f('idx_insights_why_now'), 'insights', ['why_now_score'], unique=False)
    op.create_index(op.f('idx_insights_revenue_potential'), 'insights', ['revenue_potential'], unique=False)
    op.create_index(op.f('idx_insights_problem'), 'insights', ['problem_score'], unique=False)
    op.create_index(op.f('idx_insights_opportunity'), 'insights', ['opportunity_score'], unique=False)
    op.create_index(op.f('idx_insights_go_to_market'), 'insights', ['go_to_market_score'], unique=False)
    op.create_index(op.f('idx_insights_founder_fit'), 'insights', ['founder_fit_score'], unique=False)
    op.create_index(op.f('idx_insights_feasibility'), 'insights', ['feasibility_score'], unique=False)
    op.create_index(op.f('idx_insights_execution'), 'insights', ['execution_difficulty'], unique=False)
    op.create_index(op.f('idx_insights_enhanced_filter'), 'insights', ['opportunity_score', 'feasibility_score', 'revenue_potential'], unique=False)
    op.create_index(op.f('idx_insights_edited_by'), 'insights', ['edited_by'], unique=False)
    op.create_index(op.f('idx_insights_admin_status'), 'insights', ['admin_status'], unique=False)
    op.drop_index(op.f('ix_insight_interactions_user_id'), table_name='insight_interactions')
    op.drop_index(op.f('ix_insight_interactions_interaction_type'), table_name='insight_interactions')
    op.drop_index(op.f('ix_insight_interactions_insight_id'), table_name='insight_interactions')
    op.drop_index(op.f('ix_insight_interactions_created_at'), table_name='insight_interactions')
    op.create_index(op.f('idx_interactions_user_insight'), 'insight_interactions', ['user_id', 'insight_id'], unique=False)
    op.create_index(op.f('idx_interactions_user'), 'insight_interactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_interactions_type_created'), 'insight_interactions', ['interaction_type', 'created_at'], unique=False)
    op.create_index(op.f('idx_interactions_type'), 'insight_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('idx_interactions_insight'), 'insight_interactions', ['insight_id'], unique=False)
    op.create_index(op.f('idx_interactions_created'), 'insight_interactions', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_custom_analyses_user_id'), table_name='custom_analyses')
    op.drop_index(op.f('ix_custom_analyses_status'), table_name='custom_analyses')
    op.drop_index(op.f('ix_custom_analyses_created_at'), table_name='custom_analyses')
    op.create_index(op.f('idx_analyses_user_status'), 'custom_analyses', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_analyses_user'), 'custom_analyses', ['user_id'], unique=False)
    op.create_index(op.f('idx_analyses_status'), 'custom_analyses', ['status'], unique=False)
    op.create_index(op.f('idx_analyses_created'), 'custom_analyses', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_agent_execution_logs_status'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_source'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_created_at'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_agent_type'), table_name='agent_execution_logs')
    op.create_index(op.f('idx_agent_logs_type_status'), 'agent_execution_logs', ['agent_type', 'status'], unique=False)
    op.create_index(op.f('idx_agent_logs_source'), 'agent_execution_logs', ['source'], unique=False)
    op.create_index(op.f('idx_agent_logs_created'), 'agent_execution_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_admin_users_user_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_role'), table_name='admin_users')
    op.create_index(op.f('idx_admin_users_user'), 'admin_users', ['user_id'], unique=False)
    op.create_index(op.f('idx_admin_users_role'), 'admin_users', ['role'], unique=False)
    op.drop_index(op.f('ix_tenant_users_user_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_team_invitations_token'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_team_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_email'), table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index(op.f('ix_shared_insights_team_id'), table_name='shared_insights')
    op.drop_index(op.f('ix_shared_insights_insight_id'), table_name='shared_insights')
    op.drop_table('shared_insights')
    op.drop_index(op.f('ix_payment_history_subscription_id'), table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_index(op.f('ix_api_key_usage_logs_created_at'), table_name='api_key_usage_logs')
    op.drop_index(op.f('ix_api_key_usage_logs_api_key_id'), table_name='api_key_usage_logs')
    op.drop_table('api_key_usage_logs')
    op.drop_index(op.f('ix_tenants_subdomain'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_owner_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_index(op.f('ix_teams_owner_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
