"""Create raw_signals table

Revision ID: 955917ed64f1
Revises: 
Create Date: 2026-01-18 01:32:02.864154

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '955917ed64f1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Data source: reddit, product_hunt, google_trends'),
    sa.Column('url', sa.Text(), nullable=False, comment='Source URL where data was scraped'),
    sa.Column('content', sa.Text(), nullable=False, comment='Scraped content in markdown format'),
    sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='Additional structured data (upvotes, comments, etc.)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when signal was created'),
    sa.Column('processed', sa.Boolean(), nullable=False, comment='Flag indicating if signal has been analyzed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_signals_created_at'), 'raw_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_raw_signals_id'), 'raw_signals', ['id'], unique=False)
    op.create_index(op.f('ix_raw_signals_processed'), 'raw_signals', ['processed'], unique=False)
    op.create_index(op.f('ix_raw_signals_source'), 'raw_signals', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_signals_source'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_processed'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_id'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_created_at'), table_name='raw_signals')
    op.drop_table('raw_signals')
    # ### end Alembic commands ###
