"""Add foreign key constraints to competitor tables

Revision ID: b94254847a13
Revises: 448430173035
Create Date: 2026-01-28 10:13:08.476141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b94254847a13'
down_revision: Union[str, Sequence[str], None] = '448430173035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('market_position', sa.String(length=50), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.String(length=500), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('positioning_x', sa.Integer(), nullable=True),
    sa.Column('positioning_y', sa.Integer(), nullable=True),
    sa.Column('last_scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scrape_status', sa.String(length=50), nullable=True),
    sa.Column('scrape_error', sa.Text(), nullable=True),
    sa.Column('analysis_generated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('analysis_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_profiles_created_at'), 'competitor_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_competitor_profiles_insight_id'), 'competitor_profiles', ['insight_id'], unique=False)
    op.create_index('ix_competitor_profiles_insight_id_name', 'competitor_profiles', ['insight_id', 'name'], unique=False)
    op.create_index('ix_competitor_profiles_last_scraped_at', 'competitor_profiles', ['last_scraped_at'], unique=False)
    op.create_index('ix_competitor_profiles_market_position', 'competitor_profiles', ['market_position'], unique=False)
    op.create_index(op.f('ix_competitor_profiles_name'), 'competitor_profiles', ['name'], unique=False)
    op.create_table('competitor_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changes_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('scrape_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_snapshots_competitor_id'), 'competitor_snapshots', ['competitor_id'], unique=False)
    op.create_index('ix_competitor_snapshots_competitor_id_scraped_at', 'competitor_snapshots', ['competitor_id', 'scraped_at'], unique=False)
    op.create_index(op.f('ix_competitor_snapshots_scraped_at'), 'competitor_snapshots', ['scraped_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_snapshots_scraped_at'), table_name='competitor_snapshots')
    op.drop_index('ix_competitor_snapshots_competitor_id_scraped_at', table_name='competitor_snapshots')
    op.drop_index(op.f('ix_competitor_snapshots_competitor_id'), table_name='competitor_snapshots')
    op.drop_table('competitor_snapshots')
    op.drop_index(op.f('ix_competitor_profiles_name'), table_name='competitor_profiles')
    op.drop_index('ix_competitor_profiles_market_position', table_name='competitor_profiles')
    op.drop_index('ix_competitor_profiles_last_scraped_at', table_name='competitor_profiles')
    op.drop_index('ix_competitor_profiles_insight_id_name', table_name='competitor_profiles')
    op.drop_index(op.f('ix_competitor_profiles_insight_id'), table_name='competitor_profiles')
    op.drop_index(op.f('ix_competitor_profiles_created_at'), table_name='competitor_profiles')
    op.drop_table('competitor_profiles')
    # ### end Alembic commands ###
