import Link from "next/link";
import { FileText } from "lucide-react";

export const metadata = {
  title: "Terms of Service",
  description: "Terms of Service for StartInsight — AI-powered startup intelligence platform.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using StartInsight ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service. These Terms apply to all visitors, users, and others who access or use the Service.`,
  },
  {
    title: "2. Description of Service",
    content: `StartInsight is an AI-powered platform that helps entrepreneurs discover, validate, and develop startup ideas. We provide market intelligence, trend analysis, and business opportunity scoring through automated data processing and AI-generated insights.`,
  },
  {
    title: "3. Accounts",
    content: `You must create an account to access most features of the Service. You are responsible for safeguarding your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these Terms.`,
  },
  {
    title: "4. Subscription and Billing",
    content: `StartInsight offers both free and paid subscription tiers. Paid subscriptions are billed on a monthly or annual basis. You authorize us to charge your payment method for all fees incurred. Subscriptions automatically renew unless cancelled before the renewal date. Refunds for annual plans are available within 30 days of purchase; monthly plans are non-refundable.`,
  },
  {
    title: "5. Acceptable Use",
    content: `You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to gain unauthorized access to any part of the Service; (c) scrape, crawl, or otherwise extract data from the Service in bulk without our written consent; (d) use AI-generated insights to mislead investors or consumers; (e) resell or redistribute our content without a valid API or reseller agreement.`,
  },
  {
    title: "6. Intellectual Property",
    content: `The Service and its original content, features, and functionality are owned by StartInsight and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws. AI-generated insights delivered to you are licensed for your personal or internal business use only.`,
  },
  {
    title: "7. User Content",
    content: `You retain ownership of any content you submit to the Service ("User Content"). By submitting User Content, you grant StartInsight a worldwide, non-exclusive, royalty-free license to use, process, and display such content solely to provide and improve the Service.`,
  },
  {
    title: "8. Disclaimer of Warranties",
    content: `The Service is provided "as is" and "as available" without any warranties of any kind, express or implied. AI-generated insights are provided for informational purposes only and do not constitute financial, legal, or business advice. We do not guarantee the accuracy, completeness, or usefulness of any insights generated by our platform.`,
  },
  {
    title: "9. Limitation of Liability",
    content: `To the maximum extent permitted by law, StartInsight shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of the Service. Our total liability to you for any claims shall not exceed the amount you paid us in the 12 months preceding the claim.`,
  },
  {
    title: "10. Termination",
    content: `We may terminate or suspend your account and access to the Service at any time, with or without cause, with or without notice. Upon termination, your right to use the Service will immediately cease. All provisions of these Terms which by their nature should survive termination shall survive.`,
  },
  {
    title: "11. Governing Law",
    content: `These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which StartInsight operates, without regard to its conflict of law provisions. Any disputes shall be resolved through binding arbitration in accordance with the rules of the relevant arbitration body.`,
  },
  {
    title: "12. Changes to Terms",
    content: `We reserve the right to modify these Terms at any time. We will provide notice of significant changes by updating the "Last Updated" date below and, for material changes, by sending an email to your registered address. Your continued use of the Service after changes take effect constitutes acceptance of the revised Terms.`,
  },
  {
    title: "13. Contact Us",
    content: `If you have questions about these Terms, please contact us at legal@startinsight.co or through our contact page.`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Hero */}
      <section className="border-b bg-muted/30">
        <div className="container mx-auto px-4 py-16 text-center">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-primary/10 mb-6">
            <FileText className="h-7 w-7 text-primary" />
          </div>
          <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Please read these terms carefully before using StartInsight.
          </p>
          <p className="text-sm text-muted-foreground mt-4">Last updated: February 20, 2026</p>
        </div>
      </section>

      {/* Content */}
      <section className="container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto space-y-10">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className="text-xl font-semibold mb-3">{section.title}</h2>
              <p className="text-muted-foreground leading-relaxed">{section.content}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer note */}
      <section className="border-t bg-muted/30">
        <div className="container mx-auto px-4 py-8 text-center">
          <p className="text-sm text-muted-foreground">
            Questions about these terms?{" "}
            <Link href="/contact" className="text-primary underline underline-offset-4">
              Contact our team
            </Link>{" "}
            or email{" "}
            <a href="mailto:legal@startinsight.co" className="text-primary underline underline-offset-4">
              legal@startinsight.co
            </a>
          </p>
        </div>
      </section>
    </div>
  );
}
